# Generated by Django 4.2.4 on 2023-11-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_booling_hotels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booling',
            new_name='Booking',
        ),
    ]
